var HMUD_Guide = [[
"Movement", [
    ["north", "Go to a north exit."],
    ["south", "Go to a south exit."],
    ["east", "Go to an east exit."],
    ["west", "Go to a west exit."],
    ["up", "Go to an exit above."],
    ["down", "Go to an exit below."],
    ["exits", "Show all the available exits."],
    ["stand", "Stand at your current location."],
    ["rest", "Rest in your current location."],
    ["sit", "Sit in your current location."],
    ["sleep", "Sleep in your current location."],
    ["wake", "Wake from your sleep."],
]], [
"Communication", [
    ["say (')", "Say something in your current location."],
    ["shout", "Shout something to all users (requires at least level 2)."],
    ["tell", "Tell another user something."],
    ["emote (:)", "Display emotion in your current location."],
    ["ask", "Ask another user a question."],
    ["whisper", "Whisper to another user."],
    ["deafen", "Toggle whether you want to hear shouting."],
]], [
"Objects", [
    ["get", "Get an object (\"take\" is the same command)."],
    ["put", "Put an object into a container."],
    ["inv", "Show your inventory."],
    ["eq", "Show the equipment you are currently wearing."],
    ["drop", "Drop an object."],
    ["wear", "Wear equipment."],
    ["remove", "Remove equipment."],
    ["wield", "Wield a weapon."],
    ["hold", "Hold an object (\"grab\" is the same command)."],
    ["recite", "Recite a scroll with a target."],
    ["give", "Give an object to a target."],
    ["examine", "Examine an object for any special attributes."],
    ["eat", "Eat some food (\"taste\" is a similar command)."],
    ["drink", "Drink some liquid to quench thirst (\"sip\" is a similar command)."],
    ["donate", "Donate an object to the donation room at the Temple of Midgaard."],
    ["junk", "Get rid of an object."],
    ["pour", "Pour liquid from one container to another."],
    ["quaff", "Drink a potion."],
    ["unlock", "Unlock a target (an object or direction)."],
    ["lock", "Unlock a target (an object or direction)."],
    ["open", "Open a target (an object or direction)."],
    ["close", "Close a target (an object or direction)."],
]], [
"Info", [
    ["look", "Look at a target (an object, a user, a direction, etc.)"],
    ["score", "Show your current progress."],
    ["attribute", "Show all your attributes (requires at least level 5)."],
    ["levels", "Show how much experience is required before gaining a level."],
    ["news", "Show recent news. For historical SillyMUD news, see the mortals board."],
    ["info", "Show basic information about features that were unique to SillyMUD."],
    ["read", "Read an object."],
    ["time", "Show the current time in the world."],
    ["showexits", "Toggle whether exits are shown after the description."],
    ["wizlist", "Show all the immortal users."],
    ["who", "Show all the users currently in the world."],
    ["whozone", "Show all the users in your zone."],
    ["world", "Show general information about the world."],
    ["help", "Get detailed help on any command."],
]], [
"Combat", [
    ["consider", "Consider whether you are able to kill a target."],
    ["kill", "Kill a target."],
    ["gain", "At a guildmaster, gain a level if enough experience has been earned (see \"levels\")."],
    ["practice", "At a guildmaster, practice a skill or spell to prepare for combat."],
    ["bite", "Bite the target to draw blood (Vampires do this to quench their thirst)."],
    ["flee", "Flee the current fight to any exit."],
    ["cast", "Cast a spell you have learned."],
    ["wimp", "Set a percentage of hit points to automatically flee at."],
    ["disarm", "Disarm the target."],
    ["group", "Group a followed user.  Remember to group yourself as leader."],
    ["follow", "Follow a user (or mob).  Required before being grouped."],
    ["auto", "Toggle looting options (\"split\" and \"loot\")."],
    ["assist", "Assist a user by fighting the user's target."],
]], [
"Utility", [
    ["save", "Save your character."],
    ["quit", "Exit the world."],
    ["! ", "Repeat the last command."],
    ["gname", "Name your group."],
    ["brief", "Toggle whether descriptions are shown."],
    ["typo", "Send typo information to the immortals."],
    ["bug", "Send bug information to the immortals."],
    ["idea", "Send idea information to the immortals."],
    ["allspells", "List all the available spells."],
]]];
